config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products do
    resources :reviews, except: [:index, :new, :show]
  end

  get "pages/:page" => "pages#show"
  root "pages#show", page: "landing_page"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews

  validates :name, :description, :price_in_cents, presence: true
  validates :price_in_cents, numericality: { only_integer: true }

  def price_in_dollars
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("$%.2f", price_in_dollars)
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product

  validates :review, presence: true

  default_scope { order("created_at DESC") }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    render template: "pages/#{params[:page]}"
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # Preloading the find_product method (at the bottom) for ONLY the following methods:
  before_action :find_product, only: [:edit, :show, :update, :destroy]
  before_action :new_product, only: [:create, :new]

  def index
    @products = Product.all
  end

  def create
    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price_in_cents = params[:product][:price_in_cents]

    if @product.save
      flash[:notice] = "Product has been successfully created."
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def new
  end

  def edit
  end

  def show
    @reviews = @product.reviews
    @review = Review.new
  end

  def update
    @product.name = params[:product][:name]
    @product.description = params[:product][:description]
    @product.price_in_cents = params[:product][:price_in_cents]

    if @product.save
      flash[:notice] = "Product has been successfully updated."
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:notice] = "Product has been successfully deleted."
      redirect_to products_path
    else
      render :show
    end
  end

  def find_product
    @product = Product.find(params[:id])
  end

  def new_product
    @product = Product.new
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :find_product, only: [:create, :edit, :update]

  def create
    @review = Review.create
    @review.review = params[:review][:review]
    @review.product = @product

    if @review.save
      flash.notice = "Review has been successfully created."
      redirect_to @product
    end
  end

  def edit
  end

  def update
    @review.review = params[:review][:review]
    @review.product = @product

    if @review.save
      flash.notice = "Review has been successfully updated."
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    if @review.destroy
      flash[:notice] = "Review has been successfully deleted."
      redirect_to product_path(params[:product_id])
    else
      render :show
    end
  end

  def find_review
    @review = Review.find(params[:id])
  end

  def find_product
    @product = Product.find(params[:product_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Rainforest</h1>
        <nav class="">
          <ul>
            <li><%= link_to("Home", root_url) %></li>
            <li><%= link_to("All Products", products_path) %></li>
            <li><%= link_to("Add a Product", "/products/new") %></li>
          </ul>
        </nav>
    </header>
    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/landing_page.html.erb
<h2>Home Page</h2>

<p>This would be a static home page in a Rails application.</p>

app/views/products/_product_form.html.erb
<%= form_for @product do |f| %>
  <div class="field">
    <p><%= f.label :name %></p>
    <p><%= f.text_field :name %></p>
  </div>

  <div class="field">
    <p><%= f.label :description %></p>
    <p><%= f.text_area :description %></p>
  </div>

  <div class="field">
    <p><%= f.label :price_in_cents, 'Price' %></p>
    <p><%= f.text_field :price_in_cents %></p>
  </div>
  <div class="field">
    <p><%= f.submit %></p>
  </div>
  <% if @product.errors.any? %>
    <div class="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %>
      prohibited this product from being saved:</h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render 'product_form', product: @product %>

app/views/products/index.html.erb
<ul>
  <% @products.each do |product| %>
    <li>
      <p><%= product.name %></p>
      <p><%= product.description %></p>
      <p><%= product.price_in_dollars %></p>
      <p><%= link_to "View Product", product_path(product) %></p>
    </li>
  <% end %>
</ul>


<!-- "/products/#{product.id}" -->

app/views/products/new.html.erb
<h1>Add a New Product</h1>
<%= render 'product_form', product: @product %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p><%= link_to "Edit Product", edit_product_path(@product) %> | <%= link_to "Delete", product_path(@product), method: :delete, data: {confirm: "Are you sure you want to delete this product?" } %> </p>
<p><%= @product.description %></p>
<p><%= @product.price_in_dollars %></p>

<h2>Product Reviews</h2>
<%= render '/reviews/reviews', review: @review %>


<h4>New Review</h4>
<%= render '/reviews/form', review: @review %>

app/views/reviews/_form.html.erb
<%= form_for([@product, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :review %><br />
    <%= f.text_area :review %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/_reviews.html.erb
<ul>
  <% @product.reviews.each do |review| %>
    <li>
      <p><%= review.review %></p>
      <p>Posted on: <%= review.created_at %></p>
      <p><%= link_to "Edit Review", edit_product_review_path(@product, review)%> | <%= link_to "Delete", product_review_path(@product, review), method: :delete, data: {confirm: "Are you sure you want to delete this review?" } %> </p>
    </li>
    <% end %>
</ul>

app/views/reviews/edit.html.erb
<%= render '/reviews/form', review: @review %>